In [7]:
import pandas as pd
from nenwin.constants import BANKNOTE_DATA_FILE

In [8]:
df = pd.read_csv(BANKNOTE_DATA_FILE)
df

variance  skewness  curtosis  entropy  forged
0      3.62160   8.66610   -2.8073 -0.44699       0
1      4.54590   8.16740   -2.4586 -1.46210       0
2      3.86600  -2.63830    1.9242  0.10645       0
3      3.45660   9.52280   -4.0112 -3.59440       0
4      0.32924  -4.45520    4.5718 -0.98880       0
...        ...       ...       ...      ...     ...
1367   0.40614   1.34920   -1.4501 -0.55949       1
1368  -1.38870  -4.87730    6.4774  0.34179       1
1369  -3.75030 -13.45860   17.5932 -2.77710       1
1370  -3.56370  -8.38270   12.3930 -1.28230       1
1371  -2.54190  -0.65804    2.6842  1.19520       1

[1372 rows x 5 columns]

In [9]:
print(len(df), f"Num real: {len(df[df['forged'] == 0])}", f"Num forgeries: {len(df[df['forged'] == 1])}" )

1372 Num real: 762 Num forgeries: 610


In [16]:
df.max()

V1        6.8248
V2       12.9516
V3       17.9274
V4        2.4495
Class     2.0000
dtype: float64

In [17]:
df.min()

V1       -7.0421
V2      -13.7731
V3       -5.2861
V4       -8.5482
Class     1.0000
dtype: float64

In [18]:
df.std()

V1       2.842763
V2       5.869047
V3       4.310030
V4       2.101013
Class    0.497103
dtype: float64

In [19]:
df.mean()

V1       0.433735
V2       1.922353
V3       1.397627
V4      -1.191657
Class    1.444606
dtype: float64

## Shuffling the dataset

In [17]:
df.sample(frac=1).reset_index(drop=True)

variance  skewness  curtosis   entropy  forged
0    -1.651400  -8.49850   9.11220  1.237900       1
1    -0.092194   0.39315  -0.32846 -0.137940       1
2     1.098700   0.63940   5.98900 -0.582770       0
3     2.716100  -4.20060   4.19140  0.169810       0
4     2.796100   2.12100   1.83850  0.383170       0
...        ...       ...       ...       ...     ...
1367  4.103800  -4.80690   3.34910 -0.492250       0
1368 -1.490400  -2.21830   1.60540  0.893940       1
1369  3.692200  -3.95850   4.34390  1.351700       0
1370  3.793500   7.98530  -2.54770 -1.872000       0
1371  3.926200   6.02990  -2.01560 -0.065531       0

[1372 rows x 5 columns]

In [43]:
 
    
tuple((x[1][:-2].to_numpy(), int(x[1][-1])) for x in df.iterrows())

((array([ 3.6216,  8.6661, -2.8073]), 0),
 (array([ 4.5459,  8.1674, -2.4586]), 0),
 (array([ 3.866 , -2.6383,  1.9242]), 0),
 (array([ 3.4566,  9.5228, -4.0112]), 0),
 (array([ 0.32924, -4.4552 ,  4.5718 ]), 0),
 (array([ 4.3684,  9.6718, -3.9606]), 0),
 (array([3.5912 , 3.0129 , 0.72888]), 0),
 (array([ 2.0922, -6.81  ,  8.4636]), 0),
 (array([ 3.2032 ,  5.7588 , -0.75345]), 0),
 (array([ 1.5356,  9.1772, -2.2718]), 0),
 (array([ 1.2247,  8.7779, -2.2135]), 0),
 (array([ 3.9899, -2.7066,  2.3946]), 0),
 (array([1.8993 , 7.6625 , 0.15394]), 0),
 (array([-1.5768, 10.843 ,  2.5462]), 0),
 (array([ 3.404 ,  8.7261, -2.9915]), 0),
 (array([ 4.6765, -3.3895,  3.4896]), 0),
 (array([2.6719 , 3.0646 , 0.37158]), 0),
 (array([0.80355, 2.8473 , 4.3439 ]), 0),
 (array([ 1.4479, -4.8794,  8.3428]), 0),
 (array([ 5.2423, 11.0272, -4.353 ]), 0),
 (array([ 5.7867,  7.8902, -2.6196]), 0),
 (array([ 0.3292, -4.4552,  4.5718]), 0),
 (array([ 3.9362, 10.1622, -3.8235]), 0),
 (array([ 0.93584,  8.8855 ,