In [2]:
import pandas as pd
from nenwin.constants import BANKNOTE_DATA_FILE

In [3]:
df = pd.read_csv(BANKNOTE_DATA_FILE)
df

variance  skewness  curtosis  entropy  forged
0      3.62160   8.66610   -2.8073 -0.44699       0
1      4.54590   8.16740   -2.4586 -1.46210       0
2      3.86600  -2.63830    1.9242  0.10645       0
3      3.45660   9.52280   -4.0112 -3.59440       0
4      0.32924  -4.45520    4.5718 -0.98880       0
...        ...       ...       ...      ...     ...
1367   0.40614   1.34920   -1.4501 -0.55949       1
1368  -1.38870  -4.87730    6.4774  0.34179       1
1369  -3.75030 -13.45860   17.5932 -2.77710       1
1370  -3.56370  -8.38270   12.3930 -1.28230       1
1371  -2.54190  -0.65804    2.6842  1.19520       1

[1372 rows x 5 columns]

In [4]:
print(len(df), f"Num real: {len(df[df['forged'] == 0])}", f"Num forgeries: {len(df[df['forged'] == 1])}" )

1372 Num real: 762 Num forgeries: 610


In [5]:
df.max()

variance     6.8248
skewness    12.9516
curtosis    17.9274
entropy      2.4495
forged       1.0000
dtype: float64

In [6]:
df.min()

variance    -7.0421
skewness   -13.7731
curtosis    -5.2861
entropy     -8.5482
forged       0.0000
dtype: float64

In [7]:
df.std()

variance    2.842763
skewness    5.869047
curtosis    4.310030
entropy     2.101013
forged      0.497103
dtype: float64

In [8]:
df.mean()

variance    0.433735
skewness    1.922353
curtosis    1.397627
entropy    -1.191657
forged      0.444606
dtype: float64

## Shuffling the dataset

In [9]:
df.sample(frac=1).reset_index(drop=True)

variance  skewness  curtosis  entropy  forged
0     -2.18020   3.37910  -1.22560 -2.66210       1
1      3.75700  -5.42360   3.82550 -1.25260       0
2     -0.88728   2.80800  -3.14320 -1.20350       1
3     -1.66410  -1.36780   1.99700  0.52283       1
4     -1.84480   1.25400   0.27218 -1.07280       1
...        ...       ...       ...      ...     ...
1367   0.37980   0.70980   0.75720 -0.44440       0
1368   3.37560  -4.09510   4.36700  1.06980       0
1369  -1.99830  -6.60720   4.82540 -0.41984       1
1370  -0.20620   9.22070  -3.70440 -6.81030       0
1371   0.52855   0.96427   4.02430 -1.04830       0

[1372 rows x 5 columns]

In [14]:
a = tuple((x[1][:-1].to_numpy().reshape((1, -1)), int(x[1][-1])) for x in df.iterrows())
a[:10]

((array([[ 3.6216 ,  8.6661 , -2.8073 , -0.44699]]), 0),
 (array([[ 4.5459,  8.1674, -2.4586, -1.4621]]), 0),
 (array([[ 3.866  , -2.6383 ,  1.9242 ,  0.10645]]), 0),
 (array([[ 3.4566,  9.5228, -4.0112, -3.5944]]), 0),
 (array([[ 0.32924, -4.4552 ,  4.5718 , -0.9888 ]]), 0),
 (array([[ 4.3684,  9.6718, -3.9606, -3.1625]]), 0),
 (array([[3.5912 , 3.0129 , 0.72888, 0.56421]]), 0),
 (array([[ 2.0922 , -6.81   ,  8.4636 , -0.60216]]), 0),
 (array([[ 3.2032 ,  5.7588 , -0.75345, -0.61251]]), 0),
 (array([[ 1.5356 ,  9.1772 , -2.2718 , -0.73535]]), 0))

In [20]:
a[0][0].shape

(1, 4)